
export const HIREST_URL_CONSTANT = {
  url:{
    VALUE_CONTENT_TYPE:'Content-Type',
    VALUE_USER_CODE:'user_code',
    VALUE_ORGNAME:'orgName',
    VALUE_TOKEN:'token'
  },
  PARAM_SURVEY_ID: 'survey_id',
  PARAM_SURVEY_PUBLISH_MODE: 'survey_publish_mode',
  PARAM_REQUEST_ID: 'request_id',
  PARAM_SURVEY_RECIPIENTS_DETAILS_ID: 'survey_recipient_details_id',
  PARAM_SURVEY_TYPE: 'survey_type',
  PARAM_ACTIVATION_CODE: 'ac',
  PARAM_EMAIL_ID: 'e',
  FIELD_SURVEY_STATUS: 'progress_status',
  FIELD_SURVEY_STATUS_INDRAFT: 'IN_DRAFT',
  FIELD_SURVEY_STATUS_COMPLETED: 'COMPLETED',
  VALUE_SURVEY_STATUS_COMPLETE: 'COMPLETE',
  VALUE_SURVEY_STATUS_INDRAFT: 'IN-DRAFT',
  FIELD_COMPLETED_PAGE_NUMBER: 'completed_page_number',
  FIELD_SURVEY_RESPONSES: 'survey_responses_json',
  FIELD_RESPONSES_ADDITIONAL_DETAILS: 'response_additional_details',
  VALUE_SUBMITTED_ON: 'SUBMITTED_ON',
  VALUE_CHANNEL: 'CHANNEL',
  VALUE_BROWSER: 'BROWSER',
  VALUE_IP_ADDRESS: 'IP_ADDRESS',
  FIELD_CREATED_BY: 'created_by',
  FIELD_UPDATED_BY: 'updated_by',
  VALUE_REQUEST_ID: 'REQUEST_ID',
  VALUE_ATTRIBUTE_NAME: 'attribute_name',
  VALUE_ATTRIBUTE_VALUE: 'attribute_value',
  FIELD_SURVEY_RESPONSES_ID: 'survey_responses_details_id',
  VALUE_DEFAULT_USER: 'ANONYMOUS_USER',
  FIELD_NAME: 'name',
  FIELD_SURVEY_ELEMENTS_JSON: 'survey_elements_json',
  FIELD_DESCRIPTION: 'description',
  VALUE_CONTENT_TYPE: 'Content-Type',
  VALUE_ORGNAME: 'orgName',
  VALUE_USER_CODE: 'user_code',
  VALUE_TOKEN: 'token',
  FIELD_CRITERIA: 'criteria',
  FIELD_COMPANY: 'company',
  FIELD_LEGAL_ENTITY_ID: 'legal_entity_id',
  FIELD_FUNCTION: 'function',
  FIELD_FUNCTION_ID: 'function_id',
  FIELD_BAND: 'band',
  FIELD_HIERARCHY_ID: 'hierarchy_id',
  FIELD_PROJECT: 'project',
  FIELD_TEAM_ID: 'team_id',
  FIELD_LOCATION: 'location',
  FIELD_LOCATION_ID: 'location_id',
  FIELD_STATUS: 'status',
  FIELD_RESOURCE_IDS: 'resource_ids',
  FIELD_SURVEY_GROUP_ID: 'survey_group_id',
  FIELD_RESOURCE_ID: 'resource_id',
  FIELD_END_TIME: 'end_time',
  FIELD_START_TIME: 'start_time',
  FIELD_VALUE: 'value',
  FIELD_SURVEY_TEMPLATE_ID: 'survey_template_id',
  MSG_CONS_SURVEY_COMPLETED: 'You have already completed your survey!!!',
  VALUE_CATEGORY: 'categories',
  VALUE_CATEGORY_ID: 'category_id',
  VALUE_CATEGORY_NAME: 'category_name',
  VALUE_CATEGORY_WEIGTHAGE: 'category_weightage',
  FIELD_LABEL: 'label',
  FIELD_SURVEY_CAMPAIGN_ID: 'survey_campaign_id',
  FIELD_SCALE: 'scale',
  FIELD_RESPONDERS: 'responders',
  FIELD_TYPE: 'type',
  FIELD_WEIGHTAGES: 'weightages',
  FIELD_DATA: 'data',
  VALUE_NO_DATA_FOUND: 'No Data Found',
  FIELD_SURVEY_EDITOR_JSON : 'survey_editor_json',
  ENUM_PUBLISH: 0,
  ENUM_CLOSED: 1,
  ENUM_ADMIN_CLOSED: 2,
  ENUM_CREATE_SURVEY_IN_DRAFT: 3,
  ENUM_ADD_QUESTION_IN_DRAFT: 4,
  ENUM_DELETE: 5,
  VALUE_PUBLISH: 'PUBLISH',
  VALUE_CLOSED: 'CLOSED',
  VALUE_ADMIN_CLOSED: 'ADMIN_CLOSED',
  VALUE_OF_DRAFT_TO_SHOW: 'Draft',
  VALUE_CREATE_SURVEY_IN_DRAFT: 'CREATE_SURVEY_IN_DRAFT',
  VALUE_ADD_QUESTIONS_IN_DRAFT: 'ADD_QUESTIONS_IN_DRAFT',
  VALUE_DELETE: 'DELETE',
  VALUE_EXPERIENCES: 'experiences',
  VALUE_EXPERIENCE_LEVEl: 'exp_level',
  VALUE_TOTAL_EXPERIENCE: 'TOTAL_EXPERIENCE',
  VALUE_RECIPIENT_PERSONAL_DETAILS: 'recipient_personal_details',
  VALUE_SALUTATION: 'salutation',
  VALUE_GIVEN_NAME: 'given_name',
  VALUE_FULL_NAME : 'family_name',
  VALUE_SURVEY_DISPATCH_DETAILS: 'survey_dispatch_details',
  VALUE_SMALL_CHANNEL: 'channel',
  VALUE_SMALL_ADDRESS: 'address',
  VALUE_END_DATE:  'end_date',
  VALUE_RECIPEINT :  'recipient',
  VALUE_TARGET_ENTITY: 'target_entity',
  VALUE_START_DATE: 'start_date',
   VALUE_ADDITIONAL_ATTRIBUTES : 'additional_attributes',
   VALUE_VALUES: 'values',
   VALUE_EMAIL_ID: 'emailId'

};
