export * from './recommended-twin-diamonds/recommended-twin-diamonds.component'
export * from './twin-diamonds.component'
export * from './twin-diamonds.module'
export * from './you-may-like-twin-diamonds/you-may-like-twin-diamonds.component'
export * from './your-marked-as-twin-diamonds/your-marked-as-twin-diamonds.component'
